Repository Team-Weather/flutter-wea-co, pull requests merged in 2024-05, with the labels that each got.

#63 Feat: WeatherRepository 인터페이스 작성
  lib/domain/weather/repository/weather_repository.dart
Labels: ✨ Feature, [PR] 리뷰요청

#60 Feat: LocationRepository 인터페이스 작성
  lib/domain/location/repository/location_repository.dart
Labels: ✨ Feature, [PR] 리뷰요청

#61 Feat: UserAuthRepository 인터페이스 작성
  lib/domain/user/repository/user_auth_repository.dart
Labels: ✨ Feature, [PR] 리뷰요청

#62 Feat: FeedRepository 인터페이스 작성
  lib/domain/feed/repository/feed_repository.dart
Labels: ✨ Feature, [PR] 리뷰요청

#64 Feat: UserRepository 인터페이스 작성
  lib/domain/user/repository/user_repository.dart
Labels: ✨ Feature, [PR] 리뷰요청

#65 Feat: UserProfileRepository 인터페이스 작성
  lib/domain/user/repository/user_profile_repository.dart
Labels: ✨ Feature, [PR] 리뷰요청

#68 Feat:domain model copyWith() 추가 및 일부 createdAt 추가
  lib/domain/feed/model/feed.dart
  lib/domain/location/model/location.dart
  lib/domain/profile_image/model/profile_image.dart
  lib/domain/user/model/user_auth.dart
  lib/domain/user/model/user_profile.dart
  lib/domain/weather/model/daily_location_weather.dart
  lib/domain/weather/model/weather.dart
  lib/domain/weather/model/weather_background_image.dart
Labels: ✨ Feature, [PR] 리뷰요청

#66 Feat/#29 get user page user profile use case
  lib/domain/user/repository/user_profile_repository.dart
  lib/domain/user/use_case/get_user_page_user_profile_use_case.dart
  test/domain/user/use_case/get_user_page_user_profile_use_case.dart
  test/mock/data/user/repository/mock_user_profile_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#72 Feat/#20 get detail feed detail use case
  lib/domain/feed/repository/feed_repository.dart
  lib/domain/feed/use_case/get_detail_feed_detail_use_case.dart
  test/domain/feed/use_case/get_detail_feed_detail_use_case_test.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#69 Feat/#23 get detail user profile use case
  lib/domain/user/repository/user_profile_repository.dart
  lib/domain/user/use_case/get_detail_user_profile_use_case.dart
  test/domain/user/use_case/get_detail_user_profile_use_case_test.dart
Labels: ✨ Feature, [PR] 리뷰요청

#70 Feat/#9 get recommended feeds use case
  lib/domain/feed/repository/feed_repository.dart
  lib/domain/feed/use_case/get_recommended_feeds_use_case.dart
  test/domain/feed/use_case/get_detail_feed_detail_use_case_test.dart
  test/domain/feed/use_case/get_recommended_feeds_use_case.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#73 Feat/#10 sign out setting use case
  lib/domain/user/repository/user_auth_repository.dart
  lib/domain/user/use_case/sign_out_setting_use_case.dart
  test/domain/user/use_case/sign_out_setting_use_case_test.dart
  test/mock/data/user/repository/mock_sign_out_setting_case_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#76 Feat/#6 get my page user profile use case
  lib/domain/user/repository/user_profile_repository.dart
  lib/domain/user/use_case/get_my_page_user_profile_use_case.dart
  test/domain/user/use_case/get_my_page_user_profile_use_case_test.dart
  test/mock/data/user/repository/mock_user_profile_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#67 Feat/#16 get my page feeds use case
  lib/domain/feed/model/feed.dart
  lib/domain/feed/repository/feed_repository.dart
  lib/domain/feed/use_case/get_my_page_feeds_use_case.dart
  lib/domain/user/use_case/get_detail_user_profile_use_case.dart
  test/domain/feed/use_case/get_my_page_feeds_use_case.dart
  test/domain/user/use_case/get_detail_user_profile_use_case_test.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
  test/mock/data/user/repository/mock_user_profile_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#79 Feat/#32 get user page feeds use case
  lib/domain/feed/use_case/get_user_page_feeds_use_case.dart
  test/domain/feed/use_case/get_user_page_feeds_use_case_test.dart
Labels: ✨ Feature, [PR] 리뷰요청

#75 Feat/#8 save origin image use case
  lib/domain/common/file/repository/file_repository.dart
  lib/domain/common/file/use_case/save_origin_image_use_case.dart
  test/domain/common/file/save_origin_image_use_case.dart
  test/domain/user/use_case/get_user_page_user_profile_use_case.dart
  test/mock/data/common/repository/mock_file_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#78 Feat/#21 remove my page feed use case
  lib/domain/feed/repository/feed_repository.dart
  lib/domain/feed/use_case/remove_my_page_feed_use_case.dart
  test/domain/user/use_case/remove_my_page_feed_use_case.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#80 Feat/#37 refresh user page use case
  lib/domain/common/use_case/refresh_user_page_use_case.dart
  test/domain/common/use_case/refresh_user_page_use_case_test.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
  test/mock/data/feed/use_case/mock_get_user_page_feeds_use_case.dart
  test/mock/data/user/use_case/mock_get_user_page_user_profile_use_case.dart
Labels: ✨ Feature, [PR] 리뷰요청

#74 Feat/#11 log out setting use case
  lib/domain/user/repository/user_repository.dart
  lib/domain/user/use_case/log_out_setting_use_case.dart
  test/domain/user/use_case/log_out_setting_use_case_test.dart
  test/mock/data/user/repository/mock_user_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#83 Feat/#14 get origin image use case
  lib/domain/common/file/repository/file_repository.dart
  lib/domain/common/file/use_case/get_origin_image_use_case.dart
  test/domain/common/file/get_origin_image_use_case_test.dart
  test/domain/common/file/save_origin_image_use_case.dart
  test/mock/data/common/file/repository/mock_file_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#77 Feat/#38 get edit location use case
  lib/domain/location/repository/location_repository.dart
  lib/domain/location/use_case/get_edit_location_use_case.dart
  test/domain/location/use_case/get_edit_location_use_case_test.dart
  test/mock/data/location/repository/mock_location_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#87 Feat/#5 get home location use case
  lib/domain/location/repository/location_repository.dart
  lib/domain/location/use_case/get_home_location_use_case.dart
  test/domain/location/use_case/get_edit_location_use_case_test.dart
  test/domain/location/use_case/get_home_location_use_case_test.dart
  test/mock/data/location/repository/mock_location_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#86 Feat/#13 get home image use case
  lib/domain/weather/repository/weather_background_image_repository.dart
  lib/domain/weather/use_case/get_home_image_use_case.dart
  test/domain/common/file/save_origin_image_use_case_test.dart
  test/domain/feed/use_case/get_my_page_feeds_use_case_test.dart
  test/domain/feed/use_case/get_recommended_feeds_use_case_test.dart
  test/domain/user/use_case/get_user_page_user_profile_use_case_test.dart
  test/domain/user/use_case/remove_my_page_feed_use_case_test.dart
  test/domain/weather/use_case/get_home_image_use_case_test.dart
  test/mock/data/weather/repository/mock_weather_background_image_repository.dart
Labels: ✨ Feature, [PR] 리뷰요청

#85 Feat/#3-GetHomeWeatherUseCase 및 테스트 코드 작성
  lib/domain/weather/repository/daily_location_weather_repository.dart
  lib/domain/weather/repository/weather_repository.dart
  lib/domain/weather/use_case/get_daily_location_weather_use_case.dart
  test/domain/weather/use_case/get_daily_location_weather_use_case_test.dart
  test/mock/data/weather/mock_daily_location_weather_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#92 Feat/#91 http client dio
  lib/core/dio/base_dio.dart
  pubspec.yaml
Labels: ✨ Feature

#90 Feat/#30 save edit feed use case
  lib/domain/feed/model/feed.dart
  lib/domain/feed/repository/feed_repository.dart
  lib/domain/feed/use_case/save_edit_feed_use_case.dart
  test/domain/feed/use_case/save_edit_feed_use_case_test.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#82 Feat/#4 save cropped image use case
  lib/domain/common/repository/image_repository.dart
  lib/domain/common/use_case/save_cropped_image_use_case.dart
  test/domain/feed/use_case/save_cropped_image_use_case_test.dart
  test/mock/data/feed/repository/mock_image_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#88 Feat/#12 get cropped image use case
  lib/domain/common/file/repository/file_repository.dart
  lib/domain/common/file/use_case/get_cropped_image_use_case.dart
  test/domain/common/file/get_cropped_image_use_case_test.dart
  test/mock/data/common/file/repository/mock_file_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#89 Feat/#17 get ootd feeds use case
  lib/domain/feed/repository/feed_repository.dart
  lib/domain/feed/use_case/get_ootd_feeds_use_case.dart
  test/domain/feed/use_case/get_ootd_feeds_use_case_test.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#94 Feat/#26 get edit weather use case
  lib/domain/weather/repository/weather_repository.dart
  lib/domain/weather/use_case/get_edit_weather_use_case.dart
  test/domain/weather/use_case/get_edit_weather_use_case_test.dart
  test/mock/data/weather/repository/mock_weather_repository.dart
Labels: ✨ Feature, [PR] 리뷰요청

#96 Feat/#2 sign in user use case
  lib/domain/user/repository/user_auth_repository.dart
  lib/domain/user/use_case/sign_in_user_use_case.dart
  test/domain/user/use_case/sign_in_user_use_case_test.dart
  test/mock/data/user/repository/mock_sign_out_setting_case_repository_impl.dart
  test/mock/data/user/repository/mock_user_auth_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#95 Feat/#1 sign up user use case
  lib/domain/user/repository/user_repository.dart
  lib/domain/user/use_case/sign_up_user_use_case.dart
  test/domain/user/use_case/log_out_setting_use_case_test.dart
  test/lib/domain/user/use_case/sign_up_user_use_case_test.dart
  test/mock/data/user/repository/mock_user_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#101 Feat/#98 user profile refactor
  lib/domain/common/use_case/refresh_user_page_use_case.dart
  lib/domain/user/use_case/get_my_profile_use_case.dart
  lib/domain/user/use_case/get_user_page_user_profile_use_case.dart
  lib/domain/user/use_case/get_user_profile_use_case.dart
  test/domain/common/use_case/refresh_user_page_use_case_test.dart
  test/domain/user/use_case/get_my_profile_use_case_test.dart
  test/domain/user/use_case/get_user_page_user_profile_use_case_test.dart
  test/domain/user/use_case/get_user_profile_use_case_test.dart
  test/mock/data/user/use_case/mock_get_user_profile_use_case.dart
Labels: 🛠️ Refactor, [PR] 리뷰요청

#102 Feat/#100 location repository refactor
  lib/domain/location/repository/location_repository.dart
  lib/domain/location/use_case/get_home_location_use_case.dart
  lib/domain/location/use_case/get_location_use_case.dart
  test/domain/location/use_case/get_edit_location_use_case_test.dart
  test/domain/location/use_case/get_home_location_use_case_test.dart
  test/domain/location/use_case/get_location_use_case_test.dart
  test/mock/data/location/repository/mock_location_repository_impl.dart
Labels: 🛠️ Refactor, [PR] 리뷰요청

#106 Refactor: dailyLocationWeather UseCase 및 Repository 리팩토링
  lib/domain/weather/repository/daily_location_weather_repository.dart
  lib/domain/weather/repository/weather_repository.dart
  lib/domain/weather/use_case/get_daily_location_weather_use_case.dart
  lib/domain/weather/use_case/get_edit_weather_use_case.dart
  test/domain/weather/use_case/get_daily_location_weather_use_case_test.dart
  test/domain/weather/use_case/get_edit_weather_use_case_test.dart
  test/mock/data/weather/mock_daily_location_weather_repository_impl.dart
  test/mock/data/weather/repository/mock_weather_repository.dart
Labels: 🛠️ Refactor, [PR] 리뷰요청

#105 Feat/#97 data source file repository refactor
  lib/domain/common/file/model/profile_image.dart
  lib/domain/common/file/repository/file_repository.dart
  lib/domain/common/file/use_case/get_background_image_list_use_case.dart
  lib/domain/common/file/use_case/get_cropped_image_use_case.dart
  lib/domain/common/file/use_case/get_image_use_case.dart
  lib/domain/common/file/use_case/get_origin_image_use_case.dart
  lib/domain/common/file/use_case/get_profile_image_list_use_case.dart
  lib/domain/common/file/use_case/save_image_use_case.dart
  lib/domain/common/file/use_case/save_origin_image_use_case.dart
  lib/domain/common/repository/image_repository.dart
  lib/domain/common/use_case/save_cropped_image_use_case.dart
  lib/domain/weather/repository/weather_background_image_repository.dart
  lib/domain/weather/use_case/get_home_image_use_case.dart
  test/domain/common/file/get_cropped_image_use_case_test.dart
  test/domain/common/file/get_origin_image_use_case_test.dart
  test/domain/common/file/save_origin_image_use_case_test.dart
  test/domain/common/file/use_case/get_background_image_list_use_case_test.dart
  test/domain/common/file/use_case/get_image_use_case_test.dart
  test/domain/common/file/use_case/refresh_user_page_use_case_test.dart
  test/domain/common/file/use_case/save_image_use_case_test.dart
  test/domain/feed/use_case/save_cropped_image_use_case_test.dart
  test/mock/assets/test_file.txt
  test/mock/data/common/file/repository/mock_file_repository_impl.dart
  test/mock/data/feed/repository/mock_image_repository_impl.dart
  test/mock/data/weather/repository/mock_weather_background_image_repository.dart
Labels: ✨ Feature, 🛠️ Refactor, [PR] 리뷰요청

#107 Refactor/#103 userAuth repository refactor
  lib/domain/user/repository/user_auth_repository.dart
  lib/domain/user/repository/user_repository.dart
  lib/domain/user/use_case/log_out_setting_use_case.dart
  lib/domain/user/use_case/log_out_use_case.dart
  lib/domain/user/use_case/sign_in_use_case.dart
  lib/domain/user/use_case/sign_out_use_case.dart
  lib/domain/user/use_case/sign_up_use_case.dart
  test/domain/user/use_case/log_out_setting_use_case_test.dart
  test/domain/user/use_case/log_out_use_case_test.dart
  test/domain/user/use_case/sign_in_use_case_test.dart
  test/domain/user/use_case/sign_out_setting_use_case_test.dart
  test/domain/user/use_case/sign_out_use_case_test.dart
  test/domain/user/use_case/sign_up_use_case_test.dart
  test/mock/data/user/repository/mock_sign_out_setting_case_repository_impl.dart
  test/mock/data/user/repository/mock_user_auth_repository_impl.dart
  test/mock/data/user/repository/mock_user_repository_impl.dart
Labels: 🛠️ Refactor, [PR] 리뷰요청

#108 Feat/#104 feed refactor
  lib/domain/feed/repository/feed_repository.dart
  lib/domain/feed/use_case/get_recommended_feeds_use_case.dart
  test/domain/feed/use_case/get_recommended_feeds_use_case_test.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
Labels: 🛠️ Refactor, [PR] 리뷰요청

#112 Feat/#34 data source remote location data source
  lib/core/dio/base_dio.dart
  lib/core/dio/base_response.dart
  lib/core/exception/network_exception.dart
  lib/data/location/data_source/remote_data_source/kakao_reverse_geo_coder_api.dart
  lib/data/location/data_source/remote_data_source/remote_location_data_source.dart
Labels: ✨ Feature, [PR] 리뷰요청

#109 Feat/#36 device gps service
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/core/gps/gps_helper.dart
  lib/core/gps/gps_permission_status.dart
  pubspec.yaml
Labels: ✨ Feature, [PR] 리뷰요청

#114 Feat/#111 hive wrapper
  lib/core/hive/hive_wrapper.dart
  lib/domain/location/model/location.dart
  lib/domain/weather/data_source/local_daily_location_weather_data_source.dart
  lib/domain/weather/data_source/local_daily_location_weather_data_source_impl.dart
  lib/domain/weather/data_source/remote_daily_location_weather_data_source.dart
  lib/domain/weather/model/daily_location_weather.dart
  lib/domain/weather/model/weather.dart
  lib/main.dart
  pubspec.yaml
Labels: ✨ Feature, [PR] 리뷰요청

#117 Feat/#42 remote user profile data source
  lib/domain/user/data_source/remote_user_profile_data_source.dart
  lib/domain/user/data_source/remote_user_profile_date_source_impl.dart
  lib/domain/user/model/user_profile.dart
  pubspec.yaml
  test/domain/user/data_source/remote_user_profile_data_source_test.dart
Labels: ✨ Feature, [PR] 리뷰요청

#119 Feat/#115 data source local file data source
  lib/core/gps/gps_helper.dart
  lib/core/path_provider/path_provider_service.dart
  lib/data/file/data_source/local/local_file_data_source.dart
  lib/data/file/data_source/local/local_file_data_source_impl.dart
  pubspec.yaml
  test/data/file/data_source/local_file_data_source_test.dart
  test/mock/assets/test_file.txt
  test/mock/assets/test_image.png
  test/mock/assets/test_image2.png
  test/mock/data/common/file/repository/mock_path_provider_service.dart
Labels: ✨ Feature, [PR] 리뷰요청

#120 Feat/#110 firebase wrapper
  lib/core/firebase/firebase_service.dart
  lib/data/user/data_source/firebase_user_auth_data_source.dart
  lib/data/user/data_source/user_auth_data_source.dart
Labels: ✨ Feature, [PR] 리뷰요청

#118 Feat/#113 remote weather datasource
  lib/core/config/meteo_config.dart
  lib/core/exception/custom_business_exception.dart
  lib/core/exception/internal_server_exception.dart
  lib/core/exception/not_found_exception.dart
  lib/data/common/http/status_code_handler.dart
  lib/data/weather/data_source/remote_data_source/meteo_weather_api.dart
  lib/data/weather/data_source/remote_data_source/remote_weather_data_source.dart
  lib/data/weather/dto/daily_dto.dart
  lib/data/weather/dto/hourly_dto.dart
  lib/data/weather/dto/weather_dto.dart
  lib/main.dart
  pubspec.yaml
  test/data/weather/data_source/remote_data_source/meteo_weather_api_test.dart
  test/mock/core/dio/mock_meteo_dio.dart
Labels: ✨ Feature

#127 Feat/#123 data source remote profile image data source
  lib/data/user/data_source/remote_profile_image_data_source.dart
  lib/data/user/data_source/remote_profile_image_data_source_impl.dart
  test/data/user/data_source/remote_profile_image_data_source_impl_test.dart
Labels: ✨ Feature, [PR] 리뷰요청

#131 Feat/#41 sub remote feed data source
  lib/common/convertor.dart
  lib/data/feed/data_source/remote_feed_data_source.dart
  lib/data/feed/data_source/remote_feed_data_source_impl.dart
  lib/domain/feed/model/feed.dart
  lib/domain/location/model/location.dart
  lib/domain/weather/model/weather.dart
  test/domain/feed/data_source/remote_feed_data_source_impl_test.dart
  test/mock/data/feed/data_source/mock_remote_feed_data_source_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#128 Feat/#122 data source remote weather background image data source
  lib/data/weather/data_soruce/remote_weather_background_image_data_source.dart
  lib/data/weather/data_soruce/remote_weather_background_image_data_source_impl.dart
  lib/domain/weather/model/weather_background_image.dart
  test/data/weather/data_source/remote_weather_background_image_data_source_impl_test.dart
  test/domain/common/file/use_case/get_background_image_list_use_case_test.dart
Labels: ✨ Feature, [PR] 리뷰요청

#126 Feat/#22 repository location repository
  lib/core/gps/gps_helper.dart
  lib/core/gps/gps_position.dart
  lib/data/location/data_source/remote_data_source/kakao_reverse_geo_coder_api.dart
  lib/data/location/repository/location_repository_impl.dart
  lib/domain/location/repository/location_repository.dart
  test/data/file/data_source/local_file_data_source_test.dart
  test/data/location/repository/location_repository_impl_test.dart
  test/domain/location/use_case/get_location_use_case_test.dart
  test/mock/core/gps/mock_gps_helper_impl.dart
  test/mock/data/common/file/repository/mock_path_provider_service_impl.dart
  test/mock/data/location/data_source/mock_remote_location_data_source_impl.dart
  test/mock/data/location/repository/mock_location_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#130 Feat/#125 repository profile image repository
  lib/data/user/repository/profile_image_repository_impl.dart
  lib/domain/user/repository/profile_image_repository.dart
  test/data/user/repository/profile_image_repository_impl_test.dart
  test/mock/data/user/data_source/mock_remote_profile_image_data_source_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#129 Feat/#116 remote file data source
  lib/core/firebase/firebase_auth_service.dart
  lib/data/file/data_source/remote/remote_file_data_source.dart
  lib/data/file/data_source/remote/remote_file_data_source_impl.dart
  lib/data/user/data_source/firebase_user_auth_data_source.dart
  pubspec.yaml
  test/data/file/data_source/remote_file_data_source_test.dart
Labels: ✨ Feature, [PR] 리뷰요청

#136 Feat: RemoteFileDataSource.saveImage email 파라미터 추가
  lib/data/file/data_source/remote/remote_file_data_source.dart
  lib/data/file/data_source/remote/remote_file_data_source_impl.dart
  test/data/file/data_source/remote_file_data_source_test.dart
Labels: ✨ Feature, [PR] 리뷰요청

#133 Feat/#41 remote feed data source
  lib/common/convertor.dart
  lib/data/feed/data_source/remote_feed_data_source.dart
  lib/data/feed/data_source/remote_feed_data_source_impl.dart
  lib/domain/feed/model/feed.dart
  lib/domain/feed/repository/feed_repository.dart
  lib/domain/feed/use_case/get_recommended_feeds_use_case.dart
  lib/domain/location/model/location.dart
  lib/domain/weather/model/daily_location_weather.dart
  lib/domain/weather/model/weather.dart
  test/data/feed/data_source/remote_feed_data_source_impl_test.dart
  test/domain/feed/use_case/get_recommended_feeds_use_case_test.dart
  test/domain/weather/use_case/get_daily_location_weather_use_case_test.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#135 Feat/#124 repository weather back ground image repository
  lib/data/weather/repository/weather_background_image_repository_impl.dart
  lib/domain/weather/repository/weather_background_image_repository.dart
  test/data/weather/repository/weather_background_image_repository_impl_test.dart
  test/mock/data/weather/mock_remote_weather_background_image_data_source_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#134 Feat/#19 daily location weather repository
  lib/core/enum/season_code.dart
  lib/data/weather/data_source/local_data_source/local_daily_location_weather_data_source.dart
  lib/data/weather/data_source/local_data_source/local_daily_location_weather_data_source_impl.dart
  lib/data/weather/data_source/remote_data_source/remote_weather_background_image_data_source.dart
  lib/data/weather/data_source/remote_data_source/remote_weather_background_image_data_source_impl.dart
  lib/data/weather/mapper/daily_location_weather_mapper.dart
  lib/data/weather/repository/daily_location_weather_repository_impl.dart
  lib/data/weather/repository/weather_background_image_repository_impl.dart
  lib/domain/weather/data_source/remote_daily_location_weather_data_source.dart
  lib/domain/weather/model/daily_location_weather.dart
  test/data/feed/data_source/remote_feed_data_source_impl_test.dart
  test/data/weather/data_source/remote_data_source/remote_weather_background_image_data_source_impl_test.dart
  test/data/weather/repository/daily_location_weather_repository_impl_test.dart
  test/domain/feed/use_case/get_recommended_feeds_use_case_test.dart
  test/domain/weather/use_case/get_daily_location_weather_use_case_test.dart
  test/mock/data/weather/data_source/local_data_source/mock_local_daily_location_weather_data_source_impl.dart
  test/mock/data/weather/data_source/remote_data_source/mock_remote_weather_data_source_impl.dart
  test/mock/data/weather/mock_remote_weather_background_image_data_source_impl.dart
  test/mock/data/weather/repository/mock_daily_location_weather_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#132 Feat/#27 user profile repository
  lib/data/user/data_source/remote_user_profile_data_source.dart
  lib/data/user/data_source/remote_user_profile_date_source_impl.dart
  lib/domain/user/repository/user_profile_repository_impl.dart
  pubspec.yaml
  test/domain/user/data_source/remote_user_profile_data_source_test.dart
  test/domain/user/repository/user_profile_repository_impl_test.dart
  test/mock/core/firebase/mock_firebase_auth_service.dart
  test/mock/data/user/data_source/mock_remote_user_profile_data_source.dart
Labels: ✨ Feature, [PR] 리뷰요청

#137 Refact/file repository interface
  lib/data/user/data_source/remote_profile_image_data_source.dart
  lib/data/user/data_source/remote_profile_image_data_source_impl.dart
  lib/data/user/repository/profile_image_repository_impl.dart
  lib/domain/common/file/repository/file_repository.dart
  lib/domain/common/file/use_case/get_background_image_list_use_case.dart
  lib/domain/common/file/use_case/get_profile_image_list_use_case.dart
  lib/domain/file/repository/file_repository.dart
  lib/domain/file/use_case/get_background_image_list_use_case.dart
  lib/domain/file/use_case/get_image_use_case.dart
  lib/domain/file/use_case/get_profile_image_list_use_case.dart
  lib/domain/file/use_case/save_image_use_case.dart
  lib/domain/user/model/profile_image.dart
  lib/domain/user/repository/profile_image_repository.dart
  test/data/file/data_source/local_file_data_source_test.dart
  test/data/file/data_source/remote_file_data_source_test.dart
  test/data/user/repository/profile_image_repository_impl_test.dart
  test/data/weather/repository/weather_background_image_repository_impl_test.dart
  test/domain/file/use_case/get_background_image_list_use_case_test.dart
  test/domain/file/use_case/get_image_use_case_test.dart
  test/domain/file/use_case/refresh_user_page_use_case_test.dart
  test/domain/file/use_case/save_image_use_case_test.dart
  test/mock/core/path_provider/mock_path_provider_service_impl.dart
  test/mock/data/common/file/repository/mock_file_repository_impl.dart
  test/mock/data/file/repository/mock_file_repository_impl.dart
  test/mock/data/user/data_source/mock_remote_profile_image_data_source_impl.dart
  test/mock/data/user/repository/mock_profile_image_repository_impl.dart
  test/mock/data/weather/data_source/remote_data_source/mock_remote_weather_background_image_data_source_impl.dart
  test/mock/data/weather/repository/mock_weather_background_image_repository_impl.dart
Labels: 🛠️ Refactor, [PR] 리뷰요청

#138 Feat/#121 repository file repository
  lib/data/file/data_source/local/local_file_data_source.dart
  lib/data/file/data_source/local/local_file_data_source_impl.dart
  lib/data/file/data_source/remote/remote_file_data_source.dart
  lib/data/file/data_source/remote/remote_file_data_source_impl.dart
  lib/data/file/repository/file_repository_impl.dart
  test/data/file/data_source/local_file_data_source_test.dart
  test/data/file/data_source/remote_file_data_source_test.dart
  test/data/file/repository/file_repository_impl_test.dart
  test/mock/data/file/data_source/local/mock_local_file_data_source_impl.dart
  test/mock/data/file/data_source/remote/mock_remote_file_data_source_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#143 Feat/#28 user auth repository
  lib/data/user/repository/user_auth_repository_impl.dart
  lib/domain/user/repository/user_auth_repository.dart
  lib/domain/user/use_case/sign_up_use_case.dart
  test/data/user/repository/user_auth_repository_impl_test.dart
  test/mock/data/user/data_source/mock_remote_user_profile_data_source.dart
  test/mock/data/user/data_source/mock_user_auth_data_source.dart
  test/mock/data/user/repository/mock_user_auth_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#141 Test/#140 local daily location weather data source
  lib/core/hive/hive_wrapper.dart
  lib/data/weather/data_source/local_data_source/local_daily_location_weather_data_source_impl.dart
  lib/domain/feed/model/feed.dart
  lib/domain/location/model/location.dart
  lib/domain/weather/model/daily_location_weather.dart
  lib/domain/weather/model/weather.dart
  pubspec.yaml
  test/data/feed/data_source/remote_feed_data_source_impl_test.dart
  test/data/weather/data_source/local_data_source/local_daily_location_weather_data_source_impl_test.dart
  test/mock/core/hive/mock_hive_wrapper.dart
Labels: ✨ Feature, [PR] 리뷰요청

#145 Feat/#144 go router
  lib/core/enum/router_path.dart
  lib/core/go_router/router.dart
  lib/main.dart
  lib/presentation/home/home_screen.dart
  test/widget_test.dart
Labels: ✨ Feature, [PR] 리뷰요청

#149 Refact/firestore dto mapper
  lib/common/convertor.dart
  lib/core/firebase/firestore_dto_mapper.dart
  lib/data/feed/data_source/remote_feed_data_source.dart
  lib/data/feed/data_source/remote_feed_data_source_impl.dart
  lib/domain/feed/model/feed.dart
  lib/domain/location/model/location.dart
  lib/domain/weather/model/daily_location_weather.dart
  lib/domain/weather/model/weather.dart
  test/data/feed/data_source/remote_feed_data_source_impl_test.dart
Labels: 🛠️ Refactor, [PR] 리뷰요청

#150 Feat/#147 feed repository facade pattern
  lib/data/feed/repository/ootd_feed_repository_impl.dart
  lib/data/user/repository/user_profile_repository_impl.dart
  lib/domain/feed/repository/ootd_feed_repository.dart
  lib/domain/user/repository/user_profile_repository.dart
  test/data/feed/repository/ootd_feed_repository_impl_test.dart
  test/domain/user/repository/user_profile_repository_impl_test.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
  test/mock/data/file/repository/mock_file_repository_impl.dart
  test/mock/data/user/repository/mock_user_profile_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#152 Feat/#151 go router static
  lib/core/go_router/router_static.dart
  lib/main.dart
Labels: ✨ Feature, [PR] 리뷰요청

#142 Feat/#24 feed repository
  lib/data/feed/repository/feed_repository_impl.dart
  lib/domain/feed/repository/feed_repository.dart
  lib/domain/feed/use_case/get_my_page_feeds_use_case.dart
  lib/domain/feed/use_case/get_ootd_feeds_use_case.dart
  lib/domain/feed/use_case/get_user_page_feeds_use_case.dart
  lib/domain/feed/use_case/remove_my_page_feed_use_case.dart
  test/data/feed/data_source/remote_feed_data_source_impl_test.dart
  test/data/feed/repository/feed_repository_impl_test.dart
  test/domain/feed/use_case/get_ootd_feed_list_use_case_test.dart
  test/domain/feed/use_case/get_ootd_feeds_use_case_test.dart
  test/domain/user/use_case/remove_my_page_feed_use_case_test.dart
  test/mock/data/feed/data_source/mock_remote_feed_data_source.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#159 Feat/#46 home screen
  asset/icon/temperature_down_arrow_icon.png
  asset/icon/temperature_up_arrow_icon.png
  asset/icon/weather_clear_sky_icon.png
  asset/icon/weather_cloud_icon.png
  asset/icon/weather_drizzle_icon.png
  asset/icon/weather_fog_icon.png
  asset/icon/weather_freezing_rain_icon.png
  asset/icon/weather_partly_cloudy_icon.png
  asset/icon/weather_rain_icon.png
  asset/icon/weather_rain_shower_icon.png
  asset/icon/weather_snow_icon.png
  asset/icon/weather_thunder_storm_hail_icon.png
  asset/icon/weather_thunder_storm_icon.png
  asset/image/home_bg_sunny.jpg
  lib/common/image_path.dart
  lib/core/go_router/router.dart
  lib/domain/common/enum/weather_code.dart
  lib/main.dart
  lib/presentation/home/home_screen.dart
  lib/presentation/home/screen/home_screen.dart
  lib/presentation/home/view_model/home_screen_view_model.dart
  pubspec.yaml
Labels: ✨ Feature, [PR] 리뷰요청

#158 Feat/#157 ootd repository fix
  lib/core/di/di_setup.dart
  lib/core/di/feed/feed_di_setup.dart
  lib/core/di/user/user_di_setup.dart
  lib/data/feed/repository/ootd_feed_repository_impl.dart
  lib/domain/feed/use_case/remove_my_page_feed_use_case.dart
  lib/domain/feed/use_case/save_edit_feed_use_case.dart
  lib/main.dart
  test/data/feed/repository/ootd_feed_repository_impl_test.dart
  test/domain/feed/use_case/remove_my_page_feed_use_case_test.dart
  test/domain/feed/use_case/save_edit_feed_use_case_test.dart
  test/domain/user/use_case/remove_my_page_feed_use_case_test.dart
  test/mock/data/feed/repository/mock_feed_repository_impl.dart
  test/mock/data/feed/repository/mock_ootd_feed_repository_impl.dart
Labels: 🐞 Bug Fix, ✨ Feature, [PR] 리뷰요청

#155 Feat/#59 navigation bar UI
  lib/core/go_router/router.dart
  lib/main.dart
  lib/presentation/navigation_bar/bottom_navigation_widget.dart
  lib/presentation/navigation_bar/widget_view_sample.dart
Labels: ✨ Feature, [PR] 리뷰요청

#162 Feat/#53 ootd detail UI view model
  lib/core/go_router/router.dart
  lib/core/go_router/router_static.dart
  lib/main.dart
  lib/presentation/ootd_feed_detail/view/ootd_feed_detail.dart
  lib/presentation/ootd_feed_detail/view/pinch_zoom.dart
Labels: ✨ Feature, [PR] 리뷰요청

#153 Feat/#55 camera UI viewmodel
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/core/go_router/router.dart
  lib/main.dart
  lib/presentation/ootd_post/camera_screen.dart
  lib/presentation/ootd_post/camera_view_model.dart
  pubspec.yaml
Labels: ✨ Feature, [PR] 리뷰요청

#161 Feat/#51 ootd UI viewmodel
  lib/core/go_router/router.dart
  lib/presentation/ootd_feed/ootd_card.dart
  lib/presentation/ootd_feed/view/flip_card.dart
  lib/presentation/ootd_feed/view/ootd_feed_screen.dart
  lib/presentation/ootd_feed/view_model/ootd_feed_view_model.dart
Labels: ✨ Feature, [PR] 리뷰요청

#154 Feat/#57 sign in view
  lib/core/go_router/router.dart
  lib/core/util/validation_util.dart
  lib/main.dart
  lib/presentation/sign_in/screen/sign_in_screen.dart
Labels: ✨ Feature, [PR] 리뷰요청

#156 Feat/#52 sign up view
  lib/core/enum/gender_code.dart
  lib/core/go_router/router.dart
  lib/main.dart
  lib/presentation/sign_up/screen/sign_up_screen.dart
Labels: ✨ Feature, [PR] 리뷰요청

#163 Feat/#56 posting ootd screen UI viewmodel
  asset/image/ootd_post_image.png
  ios/Runner.xcodeproj/project.pbxproj
  lib/core/go_router/router.dart
  lib/main.dart
  lib/presentation/ootd_post/ootd_post_screen.dart
Labels: ✨ Feature, [PR] 리뷰요청

#166 Feat/#139 dialog UI
  lib/presentation/common/component/dialog/one_button_dialog.dart
  lib/presentation/common/component/dialog/two_button_dialog.dart
Labels: ✨ Feature, [PR] 리뷰요청

#165 Feat/#49 picture crop screen UI viewmodel
  android/app/src/main/AndroidManifest.xml
  lib/core/go_router/router.dart
  lib/main.dart
  lib/presentation/ootd_post/picture_crop/picture_crop_screen.dart
  pubspec.yaml
Labels: ✨ Feature, [PR] 리뷰요청

#168 Feat: Button Color 주입 받을 수 있게 변경
  lib/presentation/common/component/dialog/one_button_dialog.dart
  lib/presentation/common/component/dialog/two_button_dialog.dart
Labels: ✨ Feature, [PR] 리뷰요청

#169 Feat/#55 camera UI viewmodel
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/core/go_router/router.dart
  lib/core/go_router/router_static.dart
  lib/main.dart
  lib/presentation/ootd_post/camera_screen.dart
  lib/presentation/ootd_post/camera_view_model.dart
  lib/presentation/ootd_post/picture_crop/picture_crop_screen.dart
Labels: ✨ Feature, [PR] 리뷰요청

#173 Feat/#51 ootd UI viewmodel
  lib/common/image_path.dart
  lib/core/di/feed/feed_di_setup.dart
  lib/core/go_router/router.dart
  lib/core/go_router/router_static.dart
  lib/main.dart
  lib/presentation/home/component/recommand_ootd_list_widget.dart
  lib/presentation/ootd_feed/ootd_card.dart
  lib/presentation/ootd_feed/view/flip_card.dart
  lib/presentation/ootd_feed/view/ootd_feed_screen.dart
  lib/presentation/ootd_feed/view_model/ootd_feed_view_model.dart
  lib/presentation/ootd_feed_detail/view/ootd_feed_detail.dart
  lib/presentation/ootd_feed_detail/view_model/ootd_detail_view_model.dart
Labels: ✨ Feature, [PR] 리뷰요청

#171 Feat/#49 picture crop screen UI viewmodel
  lib/core/di/di_setup.dart
  lib/core/go_router/router.dart
  lib/presentation/ootd_post/picture_crop/picture_crop_screen.dart
  lib/presentation/ootd_post/picture_crop/picutre_crop_view_model.dart
Labels: ✨ Feature, [PR] 리뷰요청

#175 Feat/#57 sign in view
  lib/core/di/common/common_di_setup.dart
  lib/core/di/di_setup.dart
  lib/core/exception/handler/exception_message_handler.dart
  lib/core/go_router/router.dart
  lib/core/go_router/router_static.dart
  lib/data/user/data_source/firebase_user_auth_data_source.dart
  lib/presentation/common/enum/exception_alert.dart
  lib/presentation/common/state/exception_state.dart
  lib/presentation/sign_in/screen/sign_in_screen.dart
  lib/presentation/sign_in/view_model/sign_in_view_model.dart
Labels: ✨ Feature, [PR] 리뷰요청

#176 Feat/#56 posting ootd screen UI viewmodel
  lib/core/di/di_setup.dart
  lib/core/go_router/router.dart
  lib/presentation/ootd_post/camera_screen.dart
  lib/presentation/ootd_post/ootd_post_screen.dart
  lib/presentation/ootd_post/ootd_post_view_model.dart
Labels: ✨ Feature, [PR] 리뷰요청

#174 Feat/#48 app setting page screen UI viewmodel
  lib/core/enum/router_path.dart
  lib/core/go_router/router.dart
  lib/core/go_router/router_static.dart
  lib/main.dart
  lib/presentation/navigation_bar/widget_view_sample.dart
  lib/presentation/settings/screen/app_setting_policy_web_view.dart
  lib/presentation/settings/screen/app_setting_screen.dart
  lib/presentation/settings/view_model/app_setting_view_model.dart
  pubspec.yaml
Labels: ✨ Feature, [PR] 리뷰요청

#177 Feat/#52 sign up view
  lib/common/image_path.dart
  lib/core/di/di_setup.dart
  lib/core/go_router/router.dart
  lib/core/util/validation_util.dart
  lib/presentation/common/util/alert_util.dart
  lib/presentation/sign_in/screen/sign_in_screen.dart
  lib/presentation/sign_up/screen/sign_up_screen.dart
  lib/presentation/sign_up/view_model/sign_up_view_model.dart
Labels: ✨ Feature, [PR] 리뷰요청

#182 Feat/#50 user page screen UI viewmodel
  lib/core/di/di_setup.dart
  lib/core/go_router/router.dart
  lib/main.dart
  lib/presentation/user_page/component/feed_grid/feed_grid_deleted_user_widget.dart
  lib/presentation/user_page/component/feed_grid/feed_grid_empty_widget.dart
  lib/presentation/user_page/component/user_profile/user_profile_deleted_widget.dart
  lib/presentation/user_page/component/user_profile/user_profile_widget.dart
  lib/presentation/user_page/user_page_screen.dart
  lib/presentation/user_page/user_page_view_model.dart
  pubspec.yaml
Labels: ✨ Feature, [PR] 추가 기능 구현 중

#186 Feat/#185 domain daily location weather edit
  lib/data/weather/data_source/remote_data_source/meteo_weather_api.dart
  lib/data/weather/mapper/daily_location_weather_mapper.dart
  lib/data/weather/repository/daily_location_weather_repository_impl.dart
  lib/domain/weather/model/daily_location_weather.dart
  test/data/feed/data_source/remote_feed_data_source_impl_test.dart
  test/data/feed/repository/feed_repository_impl_test.dart
  test/data/weather/data_source/local_data_source/local_daily_location_weather_data_source_impl_test.dart
  test/data/weather/data_source/remote_data_source/meteo_weather_api_test.dart
  test/data/weather/repository/daily_location_weather_repository_impl_test.dart
  test/domain/feed/use_case/get_ootd_feed_list_use_case_test.dart
  test/domain/feed/use_case/get_recommended_feeds_use_case_test.dart
  test/domain/weather/use_case/get_daily_location_weather_use_case_test.dart
Labels: ✨ Feature

#188 Feat/#184 editing ootd screen ui viewmodel
  lib/core/go_router/router.dart
  lib/core/go_router/router_static.dart
  lib/presentation/ootd_post/ootd_post_screen.dart
  lib/presentation/ootd_post/ootd_post_view_model.dart
Labels: ✨ Feature, [PR] 리뷰요청

#189 Feat/#54 my page UI viewmodel
  lib/core/di/di_setup.dart
  lib/core/go_router/router.dart
  lib/main.dart
  lib/presentation/my_page/component/user_profile/my_profile_widget.dart
  lib/presentation/my_page/my_page_screen.dart
  lib/presentation/my_page/my_page_view_model.dart
Labels: ✨ Feature, [PR] 리뷰요청

#190 Feat/#47 ootd search UI view model
  lib/core/di/feed/feed_di_setup.dart
  lib/presentation/ooted_search/screen/ootd_search_screen.dart
  lib/presentation/ooted_search/view_model/ootd_search_view_model.dart
Labels: ✨ Feature, [PR] 리뷰요청

#191 Feat/#170 navigation bar UI icon design page linking
  asset/icon/weaco_cam_icon.png
  asset/icon/weaco_feed_add_icon.png
  asset/icon/weaco_feed_icon.png
  asset/icon/weaco_home_weather_icon.png
  asset/icon/weaco_mypage_icon.png
  asset/icon/weaco_photo_icon.png
  asset/icon/weaco_post_add_icon.png
  asset/icon/weaco_search_icon.png
  lib/common/image_path.dart
  lib/main.dart
  lib/presentation/navigation_bar/bottom_navigation_widget.dart
  lib/presentation/navigation_bar/floating_action_button_widget.dart
  lib/presentation/navigation_bar/widget_view_sample.dart
Labels: 🛠️ Refactor, [PR] 리뷰요청

#200 Feat/#194 my page refactor
  lib/core/di/di_setup.dart
  lib/core/go_router/router.dart
  lib/presentation/main/screen/main_screen.dart
  lib/presentation/my_page/component/user_profile/my_profile_widget.dart
  lib/presentation/my_page/my_page_screen.dart
  lib/presentation/my_page/screen/component/my_profile_widget.dart
  lib/presentation/my_page/screen/my_page_screen.dart
  lib/presentation/my_page/view_model/my_page_view_model.dart
Labels: 🐞 Bug Fix, ✨ Feature, [PR] 리뷰요청

#199 Feat/#195 auth user provider
  lib/core/di/di_setup.dart
  lib/core/firebase/firebase_auth_service.dart
  lib/core/go_router/router.dart
  lib/data/user/data_source/firebase_user_auth_data_source.dart
  lib/data/user/data_source/remote_user_profile_date_source_impl.dart
  lib/data/user/data_source/user_auth_data_source.dart
  lib/data/user/repository/user_auth_repository_impl.dart
  lib/domain/user/repository/user_auth_repository.dart
  lib/domain/user/use_case/sign_up_use_case.dart
  lib/presentation/common/user_provider.dart
  lib/presentation/sign_in/screen/sign_in_screen.dart
  lib/presentation/sign_up/screen/sign_up_screen.dart
  test/domain/user/data_source/remote_user_profile_data_source_test.dart
  test/mock/core/firebase/mock_firebase_auth_service.dart
  test/mock/data/user/data_source/mock_user_auth_data_source.dart
  test/mock/data/user/repository/mock_user_auth_repository_impl.dart
Labels: ✨ Feature, [PR] 리뷰요청

#203 Feat/#201 user page refactor
  lib/core/di/di_setup.dart
  lib/core/go_router/router.dart
  lib/core/go_router/router_static.dart
  lib/presentation/my_page/screen/my_page_screen.dart
  lib/presentation/user_page/component/user_profile/user_profile_deleted_widget.dart
  lib/presentation/user_page/screen/component/feed_grid/feed_grid_deleted_user_widget.dart
  lib/presentation/user_page/screen/component/feed_grid/feed_grid_empty_widget.dart
  lib/presentation/user_page/screen/component/user_profile/user_profile_deleted_widget.dart
  lib/presentation/user_page/screen/component/user_profile/user_profile_widget.dart
  lib/presentation/user_page/screen/user_page_screen.dart
  lib/presentation/user_page/user_page_screen.dart
  lib/presentation/user_page/view_model/user_page_view_model.dart
Labels: 🐞 Bug Fix, ✨ Feature, [PR] 리뷰요청

#205 Feat/#204 ootd search page refactor
  lib/presentation/ooted_search/screen/ootd_search_screen.dart
  lib/presentation/ooted_search/view_model/ootd_search_view_model.dart
Labels: 🐞 Bug Fix, [PR] 리뷰요청

#207 Feat/#192 login nudge
  lib/common/colors.dart
  lib/core/go_router/router.dart
  lib/presentation/common/component/bottom_sheet/custom_bottom_sheet.dart
  lib/presentation/home/component/recommand_login_bottom_sheet_widget.dart
  lib/presentation/home/component/recommand_ootd_list_widget.dart
  lib/presentation/home/component/weather_by_time_list_widget.dart
  lib/presentation/home/screen/home_screen.dart
  lib/presentation/main/screen/main_screen.dart
Labels: 🐞 Bug Fix, ✨ Feature, 🛠️ Refactor, [PR] 리뷰요청

#206 Feat/#178 ootd / ootd detail UI viewmodel refactoring
  lib/core/di/di_setup.dart
  lib/core/di/feed/feed_di_setup.dart
  lib/core/enum/weather_code.dart
  lib/core/go_router/router.dart
  lib/core/go_router/router_static.dart
  lib/data/feed/data_source/remote_feed_data_source.dart
  lib/data/feed/data_source/remote_feed_data_source_impl.dart
  lib/data/feed/repository/feed_repository_impl.dart
  lib/data/weather/mapper/daily_location_weather_mapper.dart
  lib/presentation/common/component/base_change_notifier.dart
  lib/presentation/common/component/base_state_widget.dart
  lib/presentation/common/component/exception_alert_handler.dart
  lib/presentation/common/enum/exception_alert_type.dart
  lib/presentation/common/state/base_alert_data.dart
  lib/presentation/common/state/exception_status.dart
  lib/presentation/home/component/recommand_ootd_list_widget.dart
  lib/presentation/home/component/weather_by_time_widget.dart
  lib/presentation/home/screen/home_screen.dart
  lib/presentation/home/view_model/home_screen_view_model.dart
  lib/presentation/main/screen/main_screen.dart
  lib/presentation/my_page/screen/my_page_screen.dart
  lib/presentation/ootd_feed/view/flip_card.dart
  lib/presentation/ootd_feed/view/ootd_feed_screen.dart
  lib/presentation/ootd_feed/view_model/ootd_feed_view_model.dart
  lib/presentation/ootd_feed_detail/view/ootd_feed_detail.dart
  lib/presentation/ootd_feed_detail/view_model/ootd_detail_view_model.dart
  lib/presentation/ootd_post/ootd_post_screen.dart
  lib/presentation/ooted_search/screen/ootd_search_screen.dart
  lib/presentation/user_page/screen/user_page_screen.dart
  test/data/feed/data_source/remote_feed_data_source_impl_test.dart
  test/mock/data/feed/data_source/mock_remote_feed_data_source.dart
Labels: 🐞 Bug Fix, ✨ Feature, 🛠️ Refactor, [PR] 리뷰요청

#197 Feat/#196 app setting dialog exception
  lib/presentation/common/enum/exception_alert.dart
  lib/presentation/common/util/alert_util.dart
  lib/presentation/settings/screen/app_setting_policy_web_view.dart
  lib/presentation/settings/screen/app_setting_screen.dart
  lib/presentation/settings/view_model/app_setting_view_model.dart
Labels: ✨ Feature, 🛠️ Refactor, [PR] 리뷰요청

#209 Feat: OotdDetailScreen 파라미터 전달 방식 변경
  lib/core/go_router/router.dart
  lib/core/go_router/router_static.dart
  lib/presentation/common/component/exception_alert_handler.dart
  lib/presentation/home/component/recommand_ootd_list_widget.dart
  lib/presentation/my_page/screen/my_page_screen.dart
  lib/presentation/ootd_feed/view/flip_card.dart
  lib/presentation/ootd_feed_detail/view/ootd_feed_detail.dart
  lib/presentation/ooted_search/screen/ootd_search_screen.dart
  lib/presentation/user_page/screen/user_page_screen.dart
Labels: ✨ Feature, [PR] 리뷰요청

#210 Feat/#198 picture crop screen complementary feature
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  lib/core/di/di_setup.dart
  lib/core/go_router/router.dart
  lib/presentation/main/screen/main_screen.dart
  lib/presentation/ootd_post/screen/camera_screen.dart
  lib/presentation/ootd_post/screen/ootd_post_screen.dart
  lib/presentation/ootd_post/screen/picture_crop_screen.dart
  lib/presentation/ootd_post/view_model/camera_view_model.dart
  lib/presentation/ootd_post/view_model/ootd_post_view_model.dart
  lib/presentation/ootd_post/view_model/picutre_crop_view_model.dart
Labels: 🛠️ Refactor

#211 Feat: sign up, sign in 인풋창 힌트 텍스트 정렬 및 다이얼로그 텍스트 위젯 변경
  lib/core/go_router/router_static.dart
  lib/presentation/common/component/dialog/one_button_dialog.dart
  lib/presentation/common/component/dialog/two_button_dialog.dart
  lib/presentation/home/component/recommand_login_bottom_sheet_widget.dart
  lib/presentation/sign_in/screen/sign_in_screen.dart
  lib/presentation/sign_in/view_model/sign_in_view_model.dart
  lib/presentation/sign_up/screen/sign_up_screen.dart
  lib/presentation/sign_up/view_model/sign_up_view_model.dart
Labels: ✨ Feature, [PR] 리뷰요청

#208 Feat/#202 posting ootd screen refactoring
  lib/presentation/main/screen/main_screen.dart
  lib/presentation/ootd_post/screen/ootd_post_screen.dart
  lib/presentation/ootd_post/view_model/ootd_post_view_model.dart
Labels: ✨ Feature, 🛠️ Refactor, [PR] 리뷰요청

#217 Feat: 로그인 인풋 height값 제거
  lib/presentation/sign_in/screen/sign_in_screen.dart
Labels: 🐞 Bug Fix, [PR] 리뷰요청

#218 Feat/#216 logout and signout routing and my page user data reset
  lib/core/go_router/router_static.dart
  lib/presentation/my_page/screen/my_page_screen.dart
  lib/presentation/my_page/view_model/my_page_view_model.dart
  lib/presentation/settings/screen/app_setting_screen.dart
Labels: 🐞 Bug Fix, [PR] 리뷰요청

#219 Feat/cached network image
  lib/core/di/di_setup.dart
  lib/core/di/feed/feed_di_setup.dart
  lib/core/go_router/router.dart
  lib/core/hive/hive_wrapper.dart
  lib/domain/feed/use_case/get_my_page_feeds_use_case.dart
  lib/main.dart
  lib/presentation/common/component/cached_image_widget.dart
  lib/presentation/common/extension/image_extension.dart
  lib/presentation/home/component/recommend_login_bottom_sheet_widget.dart
  lib/presentation/home/component/recommend_ootd_list_widget.dart
  lib/presentation/home/component/recommend_ootd_widget.dart
  lib/presentation/home/screen/home_screen.dart
  lib/presentation/main/screen/main_screen.dart
  lib/presentation/my_page/component/my_profile_widget.dart
  lib/presentation/my_page/screen/my_page_screen.dart
  lib/presentation/ootd_feed/component/flip_card_widget.dart
  lib/presentation/ootd_feed/screen/ootd_feed_screen.dart
  lib/presentation/ootd_feed_detail/screen/ootd_detail_screen.dart
  lib/presentation/ootd_feed_detail/screen/pinch_zoom.dart
  lib/presentation/ootd_post/screen/ootd_post_screen.dart
  lib/presentation/ootd_search/screen/ootd_search_screen.dart
  lib/presentation/ootd_search/view_model/ootd_search_view_model.dart
  lib/presentation/settings/screen/app_setting_policy_screen.dart
  lib/presentation/user_page/screen/user_page_screen.dart
  pubspec.yaml
Labels: 🛠️ Refactor, [PR] 리뷰요청

#222 Feat/#221 my page feed UI logic
  android/settings.gradle
  lib/presentation/common/util/alert_util.dart
  lib/presentation/my_page/screen/my_page_screen.dart
  lib/presentation/my_page/view_model/my_page_view_model.dart
Labels: ✨ Feature, [PR] 리뷰요청

#233 Release: v1.0.0
  lib/presentation/home/component/recommend_ootd_list_widget.dart
  lib/presentation/home/component/weather_by_time_list_widget.dart
  lib/presentation/home/screen/home_screen.dart
Labels: [PR] 리뷰요청
